import turtle

t = turtle.Turtle()

for c in ['red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red','red','blue','red' ]:
    t.color(c)
    t.speed(10)
    t.forward(75)
    t.left(90)
    t.forward(75)
    t.left(90)
    t.forward(75)
    t.left(90)
    t.forward(75)
    t.left(180)
    t.penup()
    t.forward(50)
    t.left(90)
    t.pendown()
    t.forward(20)
    t.back(70)
    t.left(90)
    t.forward(70)
    t.right(90)
    t.forward(70)
    t.right(90)
    t.forward(70)
    t.right(40)
    t.forward(35)
    t.right(50)
    t.penup()
    t.forward(75)
    t.right(135)
    t.pendown()
    t.forward(40)
    t.left(45)
    t.penup()
    t.forward(70)
    t.right(90)
    t.forward(70)
    t.right(135)
    t.pendown()
    t.forward(30)
    t.right(45)
    t.penup()
    t.forward(75)
    t.right(140)
    t.pendown()
    t.forward(33)
   
    
   